In [1]:
import pandas as pd 
from sklearn.linear_model import LogisticRegression
data = pd.read_csv("/Users/shenzongqi/Documents/Stevens_First_semester/FE541/Group_Project/breast.csv")
data.head()

Unnamed: 0       ID  clumpThickness  sizeUniformity  shapeUniformity  \
0           1  1000025               5               1                1   
1           2  1002945               5               4                4   
2           3  1015425               3               1                1   
3           4  1016277               6               8                8   
4           5  1017023               4               1                1   

   maginalAdhesion  singleEpithelialCellSize  bareNuclei  blandChromatin  \
0                1                         2         1.0               3   
1                5                         7        10.0               3   
2                1                         2         2.0               3   
3                1                         3         4.0               3   
4                3                         2         1.0               3   

   normalNucleoli  mitosis  class  
0               1        1      2  
1               2        1      2  
2               1        1      2  
3               7        1      2  
4               1        1      2

1. 查看缺失值

In [2]:
data.isnull().sum()

Unnamed: 0                   0
ID                           0
clumpThickness               0
sizeUniformity               0
shapeUniformity              0
maginalAdhesion              0
singleEpithelialCellSize     0
bareNuclei                  16
blandChromatin               0
normalNucleoli               0
mitosis                      0
class                        0
dtype: int64

In [3]:
# 用均值填充缺失值的位置
from statistics import mean
data["bareNuclei"].fillna(value=data["bareNuclei"].mean(), inplace=True)

In [4]:
data.isnull().sum()

Unnamed: 0                  0
ID                          0
clumpThickness              0
sizeUniformity              0
shapeUniformity             0
maginalAdhesion             0
singleEpithelialCellSize    0
bareNuclei                  0
blandChromatin              0
normalNucleoli              0
mitosis                     0
class                       0
dtype: int64

2. 划分数据集

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
data

Unnamed: 0       ID  clumpThickness  sizeUniformity  shapeUniformity  \
0             1  1000025               5               1                1   
1             2  1002945               5               4                4   
2             3  1015425               3               1                1   
3             4  1016277               6               8                8   
4             5  1017023               4               1                1   
..          ...      ...             ...             ...              ...   
694         695   776715               3               1                1   
695         696   841769               2               1                1   
696         697   888820               5              10               10   
697         698   897471               4               8                6   
698         699   897471               4               8                8   

     maginalAdhesion  singleEpithelialCellSize  bareNuclei  blandChromatin  \
0                  1                         2         1.0               3   
1                  5                         7        10.0               3   
2                  1                         2         2.0               3   
3                  1                         3         4.0               3   
4                  3                         2         1.0               3   
..               ...                       ...         ...             ...   
694                1                         3         2.0               1   
695                1                         2         1.0               1   
696                3                         7         3.0               8   
697                4                         3         4.0              10   
698                5                         4         5.0              10   

     normalNucleoli  mitosis  class  
0                 1        1      2  
1                 2        1      2  
2                 1        1      2  
3                 7        1      2  
4                 1        1      2  
..              ...      ...    ...  
694               1        1      2  
695               1        1      2  
696              10        2      4  
697               6        1      4  
698               4        1      4  

[699 rows x 12 columns]

In [7]:
#data.drop(columns="Unnamed: 0",inplace=True)
X = data.drop(columns="class")
y = data["class"]
X_train, X_test, y_train, y_test = train_test_split(X,y)
X_test

Unnamed: 0        ID  clumpThickness  sizeUniformity  shapeUniformity  \
640         641   1285722               4               1                1   
662         663  13454352               1               1                3   
463         464   1280258               4               1                1   
77           78   1133041               5               3                1   
49           50   1106829               7               8                7   
..          ...       ...             ...             ...              ...   
93           94   1158247               1               1                1   
348         349    832226               3               4                4   
477         478   1296263               4               1                1   
127         128   1177027               3               1                1   
241         242   1276091               3               1                1   

     maginalAdhesion  singleEpithelialCellSize  bareNuclei  blandChromatin  \
640                3                         2         1.0               1   
662                1                         2         1.0               2   
463                1                         2         1.0               1   
77                 2                         2         1.0               2   
49                 2                         4         8.0               3   
..               ...                       ...         ...             ...   
93                 1                         2         1.0               2   
348               10                         5         1.0               3   
477                1                         2         1.0               1   
127                1                         2         1.0               3   
241                3                         1         1.0               3   

     normalNucleoli  mitosis  
640               1        1  
662               1        1  
463               2        1  
77                1        1  
49                8        2  
..              ...      ...  
93                1        1  
348               3        1  
477               1        1  
127               1        1  
241               1        1  

[175 rows x 11 columns]

3. 特征工程

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
transformer = StandardScaler()
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)

4. 导入预估器

In [10]:
from sklearn.linear_model import LogisticRegression
import numpy as np

In [11]:
estimator = LogisticRegression()
estimator.fit(X_train,y_train)
predicted = estimator.predict(X_test)

In [12]:
print("Accuracy\n", np.mean(y_test == predicted))
print("Score\n", estimator.score(X_test, y_test))

Accuracy
 0.96
Score
 0.96


查看精确率召回率与F1score

In [13]:
from sklearn.metrics import classification_report
report = classification_report(y_test, predicted, labels=[2,4], target_names=["良性","恶性"])
print(report)

              precision    recall  f1-score   support

          良性       0.97      0.98      0.97       121
          恶性       0.94      0.93      0.93        54

    accuracy                           0.96       175
   macro avg       0.96      0.95      0.95       175
weighted avg       0.96      0.96      0.96       175



In [ ]:
# y_true：每个样本的真实类别，必须标记0(反例), 1(正例子)
# 将y_test转换为0，1

In [17]:
y_test.unique()

array([2, 4])

In [22]:
y_true = np.where(y_test>3, 1,0)
y_true


array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [23]:
pd.Series(y_true).unique()

array([0, 1])

In [24]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_true, predicted)

0.950566268748087