# <font color = Darkblue size = 4>Encoding of typed variables - pd.get_dummies(), LabelEncoder(), oneHotEncoder()<font>

# <font color = Darkblue size = 4>背景：
    在拿到的数据里，经常有分类型变量的存在，如下：
    球鞋品牌：Nike、adidas、 Vans、PUMA、CONVERSE
    性别：男、女
    颜色：红、黄、蓝、绿
    However,sklearn大佬不能直接分析这类变量呀。在回归，分类，聚类等机器学习算法中，特征之间距离的计算或相似度的计算是算法关键部分，而常用的距离或相似度的计算都是在欧式空间的相似度计算，计算余弦相似性，基于的就是欧式空间。于是，我们要对这些分类变量进行哑变量处理，又或者叫虚拟变量。
    缺点：当类别的数量很多时，特征空间会变得非常大。在这种情况下，一般可以用PCA来减少维度。而且one hot encoding+PCA这种组合在实际中也非常有用。有些基于树的算法在处理变量时，并不是基于向量空间度量，数值只是个类别符号，即没有偏序关系，所以不用进行独热编码。Tree Model不太需要one-hot编码： 对于决策树来说，one-hot的本质是增加树的深度。
    In summary,要是one hot encoding的类别数目不太多，可优先考虑。
    <font>



## <font color = Darkblue size = 4>一.pd.get_dummies()简单&粗暴
pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)
官网文档：
http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html

输入：array-like, Series, or DataFrame
输出：DataFrame
主要参数说明：
data : array-like, Series, or DataFrame
prefix : 给输出的列添加前缀，如prefix="A",输出的列会显示类似
prefix_sep : 设置前缀跟分类的分隔符sepration，默认是下划线"_"
一般，我们输入data就够了。如果要专门关注Nan这类东东，可设置dummy_na=True，专门生成一列数据。
见下面的栗子：（简直不要太容易）<font>

In [31]:
import numpy as np
import pandas as pd
data = pd.DataFrame({"学号":[1001,1002,1003,1004],
                    "性别":["男","女","女","男"],
                    "学历":["本科","硕士","专科","本科"]})
data

学号 性别  学历
0  1001  男  本科
1  1002  女  硕士
2  1003  女  专科
3  1004  男  本科

In [2]:
pd.get_dummies(data)

学号  性别_女  性别_男  学历_专科  学历_本科  学历_硕士
0  1001     0     1      0      1      0
1  1002     1     0      0      0      1
2  1003     1     0      1      0      0
3  1004     0     1      0      1      0

In [3]:
pd.get_dummies(data,prefix=["A","B"])

学号  A_女  A_男  B_专科  B_本科  B_硕士
0  1001    0    1     0     1     0
1  1002    1    0     0     0     1
2  1003    1    0     1     0     0
3  1004    0    1     0     1     0

# <font color = Darkblue size = 4>二.sklearn的崽一：LabelEncoder 将不连续的数字or文本进行编号
sklearn.preprocessing.LabelEncoder()
官方文档：
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html<font>

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit([1,5,67,100])
le.transform([1,1,100,67,5])
#输出： array([0,0,3,2,1])

array([0, 0, 3, 2, 1])

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1, 3, 3, 7])
LabelEncoder()
le.transform([1, 1, 3, 7])

array([0, 0, 1, 2])

In [5]:
le.classes_   #查看分类
#array([1, 2, 6])
le.inverse_transform([0, 0, 1, 2])  #transform的逆向
#array([1, 1, 2, 6])    

array([1, 1, 3, 7])

# <font color = Darkblue size = 4>三.sklearn的崽二：OneHotEncoder 对表示分类的数字进行编码，输出跟dummies一样
sklearn.preprocessing.OneHotEncoder(n_values=None, categorical_features=None, categories=None, sparse=True, dtype=<class ‘numpy.float64’>, handle_unknown=’error’)
官方文档：
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html
注意：
输入的应该是表示类别的数字，如果输入文本，会报错的。<font>

In [30]:
data

学号  性别  学历
0  1001   1   1
1  1002   0   2
2  1003   0   0
3  1004   1   1

In [32]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder()
OHE.fit(data)

OneHotEncoder()

 看到，OneHotEncoder处理不了字符串。要先用

In [33]:
data3 = le.fit_transform(data["性别"])
OHE.fit(data3.reshape(-1,1))
OHE.transform(data3.reshape(-1,1)).toarray()

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [34]:
data3

array([1, 0, 0, 1])